{% set name = "hnswlib" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b696d13f3678aa6795d054a0e8c33b3a2c8e14908432aaf4ced7ebef8290a10c

build:
  number: 2
  skip: true  # [py<37]
  script:
    # HNSWLIB_NO_NATIVE is set to build without "--march=native"
    - export HNSWLIB_NO_NATIVE=1 && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv  # [unix]
    - set HNSWLIB_NO_NATIVE=1 && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=42
    - pybind11 >=2.0
    - numpy >=1.10.0
  run:
    - python
    - numpy

test:
  imports:
    - hnswlib

about:
  home: https://github.com/nmslib/hnswlib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python bindings for Hnswlib, a fast approximate nearest neighbor search package.
  dev_url: https://github.com/nmslib/hnswlib

extra:
  recipe-maintainers:
    - yihming
    - bli25
    - yurymalkov
